services:
  pulsar:
    image: apachepulsar/pulsar:latest
    container_name: pulsar-standalone
    ports:
      - "6650:6650" # Pulsar service port
      - "8080:8080" # Pulsar admin port
    command: bin/pulsar standalone

  prometheus:
    image: prom/prometheus
    container_name: prometheus-server
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" # Prometheus server port