services:
  pulsar:
    image: apachepulsar/pulsar:latest
    container_name: pulsar-standalone
    ports:
      - "6650:6650" # Pulsar service port
      - "8080:8080" # Pulsar admin port
    command: bin/pulsar standalone
    volumes:
      - pulsar_data:/pulsar/data
      - pulsar_conf:/pulsar/conf

volumes:
  pulsar_data:
  pulsar_conf: